name: Build on push
on: [push]

jobs:
    BuildMockbird:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v6
        - name: "Install DOS C++ compiler"
          uses: open-watcom/setup-watcom@v1
          with:
            version: "1.9"
            target:  "dos"
        - name: "Compile C++ source code"
          run: |
            cd src
            wmake
            wstrip mockbird.exe
        - name: "Upload compiled executable"
          if: ${{!startsWith(github.ref, 'refs/tags/v')}}
          uses: actions/upload-artifact@v6
          with:
            name: mockbird.exe
            path: src/mockbird.exe
        - name: "Build documentation"
          uses: mattnotmitt/doxygen-action@v1.12.0
        - name: "Upload documentation"
          if: ${{!startsWith(github.ref, 'refs/tags/v')}}
          uses: actions/upload-pages-artifact@v3
          with:
            path: doc/html/
        - name: "Deploy documentation"
          id: doc
          if: ${{startsWith(github.ref, 'refs/tags/v')}}
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: doc/html
            target-folder: ${{github.ref_name}}
        - name: "Get pages URL for documentation template"
          id: get-url
          uses: tuftsrt/get-pages-url@v1
        - name: "Create draft release"
          if: ${{startsWith(github.ref, 'refs/tags/v')}}
          uses: softprops/action-gh-release@v2
          with:
            body:
              See ${{steps.get-url.outputs.url}}${{github.ref_name}} for documentation.
            files: |
              src/mockbird.exe
            draft: true
            generate_release_notes: true